// Generated by LiveScript 1.6.0
"use strict";
var sup;
sup = null;
document.addEventListener('DOMContentLoaded', function(){
  sup = YSTTS({
    token: '774532944:AAEoeYADIiKgm1Fad3gpXeBZCwSg2OcuqDY',
    chat_id: '383747467',
    username: 'testman',
    storage: window.localStorage,
    onStart: function(){
      this.sendLog('YSTTS demo started');
    },
    onStop: function(){
      if (this.error) {
        console.log(this.error);
      }
    },
    onError: function(msg){
      console.log('YSTTS error: ' + msg);
      this.stop();
    }
  });
  sup.start();
});