// Generated by LiveScript 1.6.0
"use strict";
var sup;
sup = null;
document.addEventListener('DOMContentLoaded', function(){
  sup = YSTTS({
    username: 'testman',
    token: '774532944:AAEoeYADIiKgm1Fad3gpXeBZCwSg2OcuqDY',
    chat_id: '383747467',
    onStart: function(){
      this.sendLog('YSTTS demo started');
      this.active = 1;
    },
    onStop: function(){
      console.log('YSTTS demo finished');
    },
    onUpdate: function(type){
      debugger;
      var d;
      d = this.data;
    },
    onError: function(e){
      if (this.error) {
        console.log('YSTTS error: ' + this.error);
      }
      this.stop();
    }
  });
});